version: '3'
services:
  currency_convertor:
    build:
      context: ./
      dockerfile: './dockerfile'
      target: 'builder'
    restart: 'unless-stopped'
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node
      - ./node_modules:/home/node
    env_file:
      - './.env'
    command: sh -c "npm run start:dev"
    networks:
      - currencyConvertor

networks:
  currencyConvertor:
    driver: bridge